# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('sex', models.BooleanField()),
                ('student_num', models.CharField(max_length=32)),
                ('introduction', models.TextField()),
                ('img', models.ImageField(null=True, upload_to='image/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('permission', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=16)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.Member')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cm.MyUser')),
            ],
        ),
    ]
